---

- name: clone bash git prompt
  git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: "{{ ansible_env.HOME }}/.bash-git-prompt"

###############################################################
# Uncomment the lines below if you don´t include dotfiles.yml #
###############################################################

#- name: git prompt only in repo
#  lineinfile:
#    dest: "{{ ansible_env.HOME }}/.bashrc"
#    regexp: "GIT_PROMPT_ONLY_IN_REPO="
#    line: "GIT_PROMPT_ONLY_IN_REPO=1"
#
#- name: source gitprompt.sh
#  lineinfile:
#    dest: "{{ ansible_env.HOME }}/.bashrc"
#    regexp: "gitprompt.sh"
#    line: "source ~/.bash-git-prompt/gitprompt.sh"
#
#- name: force color prompt
#  lineinfile:
#    dest: "{{ ansible_env.HOME }}/.bashrc"
#    regexp: "force_color_prompt="
#    line: "force_color_prompt=yes"
