---

- name: clone dotfiles
  git:
    repo: https://github.com/enricorufnak/dotfiles.git
    dest: "{{ ansible_env.HOME }}/setup/dotfiles"
    update: no

- name: install dofiles
  shell: "{{ ansible_env.HOME }}/setup/dotfiles/install"