---

- name: download Ubuntu dropbox package
  get_url: 
    url: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb"
    dest: "{{ ansible_env.HOME }}/setup/dropbox.deb"

- name: install Ubuntu dropbox package
  apt: 
    deb: "{{ ansible_env.HOME }}/setup/dropbox.deb"
  sudo: yes

- name: install python-gpgme to verify binary signatures
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - python-gpgme
  sudo: yes
