---

- name: download phpstorm
  get_url:
    url: "https://download.jetbrains.com/webide/PhpStorm-10.0.3.tar.gz"
    dest: "{{ ansible_env.HOME }}/setup/PhpStorm-10.0.3.tar.gz"
    timeout: 1000
    validate_certs: false

- name: install phpstorm
  unarchive:
    src: "{{ ansible_env.HOME }}/setup/PhpStorm-10.0.3.tar.gz"
    dest: "{{ ansible_env.HOME }}"
