---

- name: ensure partner repositrories added
  apt_repository:
     repo: 'deb http://archive.canonical.com/ ubuntu-xenial partner'
     state: present
     update_cache: yes

- name: install skype
  apt:
    name: "{{item}}"
    state: installed
    update_cache: yes
  become: yes
  with_items:
       - skype
